import { UserControls } from "./userControls.js";
import { Header } from "./headerComponent.js";
import { Footer } from "./footerComponent.js";
import { ShopPage } from "./shopPage.js";
import { RandomProducts } from "./randomProducts.js";
import { DropdownMenu } from "./dropdownMenu.js";
import { SearchBar } from "./searchBar.js";
import { UserLogin } from "./userLogin.js";
import { UserRegister } from "./userRegister.js";
import { ProductPage } from "./productPage.js";
import { CategoryPage } from "./categoryComponent.js";
import { SmallCart } from "./smallCartComponent.js";
import { ProductCard } from "./productCard.js";
import { AddToCartButton } from "./addTocartComponent.js";

customElements.define("custom-header", Header);
customElements.define("user-controls", UserControls);
customElements.define("custom-footer", Footer);
customElements.define("shop-page", ShopPage);
customElements.define("random-products", RandomProducts);
customElements.define("dropdown-menu", DropdownMenu);
customElements.define("search-bar", SearchBar);
customElements.define("user-login", UserLogin);
customElements.define("user-register", UserRegister);
customElements.define("product-page", ProductPage);
customElements.define("category-view", CategoryPage);
customElements.define("small-cart", SmallCart);
customElements.define("product-card", ProductCard);
customElements.define("add-to-cart-button", AddToCartButton);
